/******************************************************************************
 *
 * Project       : Graphical User Interface for SUP and PSPS
 *
 * Description   : Common libraries and tools for Operation Application GUIs
 *
 * Author        : Gennady Pospelov (IO)
 *
 * Copyright (c) : 2010-2025 ITER Organization,
 *                 CS 90 046
 *                 13067 St. Paul-lez-Durance Cedex
 *                 France
 *
 * This file is part of ITER CODAC software.
 * For the terms and conditions of redistribution or use of this software
 * refer to the file ITER-LICENSE.TXT located in the top level directory
 * of the distribution package.
 *****************************************************************************/

#include "folder_test.h"

#include "testconfig.h"  // this file is auto generated by the build system in build directory

namespace sup::gui::test
{

FolderTest::FolderTest(std::string test_home_dirname)
    : FolderOutputBasedTest(GetTestSuiteOutputDir(), std::move(test_home_dirname))
{
}

std::string GetTestSuiteOutputDir()
{
  return sup::gui::TestConfig::TestOutputDir();  // defined in auto-generated testconfig.h
}

std::string GetProjectSourceDir()
{
  return sup::gui::TestConfig::ProjectSourceDir();  // defined in auto-generated testconfig.h
}

}  // namespace sup::gui::test
